/**
 * 模拟菜单数据
 */
export const demoMenus=[
    {
        id:"001",
        name:"首页",
        path:"/index",
        icon:"mail",
        isDetail:false,
        subMenus:[],
    },
    {
        id:"002",
        name:"项目管理",
        path:"",
        icon:"appstore",
        isDetail:false,
        subMenus:[
            {
                id:"002001",
                name:"关于我们",
                path:"/about",
                icon:"qq",
                isDetail:false,
                subMenus:[
                    {
                        id:"002001001",
                        name:"关于我们详细",
                        path:'/about/:data',
                        icon:"ppmoney",
                        isDetail:true,
                    }
                ],
            },
            {
                id:"002002",
                name:"信息",
                path:"/info",
                icon:"wechat",
                isDetail:false,
                subMenus:[
                    {
                        id:"002002001",
                        name:"信息详细",
                        path:"/info/:id",
                        icon:"qq",
                        isDetail:true,
                        subMenus:[],
                    },
                ],
            }
        ],
    },
    {
        id:"003",
        name:"信息编辑",
        path:"/info/edit",
        icon:"ie",
        isDetail:false,
        subMenus:[],
    },
];